



name: CI

on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

 
jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v4

      
      - name: Build image
        run: docker build -t chopper717/my-portfolio.1 .

      - name: Push image 
        run: |
             docker login -u chopper717 -p ${{secrets.REGISTRY_PASS}}
             docker push chopper717/my-portfolio.1 
          
          
